import doc_globals

from enums import DefType
from doc_def import DocDef
from namespace_info import NamespaceInfo
from parser import Parser
from writer import Writer

class DoxygenWriter:
  def generate_text_for_file(text, filename = None):
    result = "// Generated by docgen\n"
    if filename:
      result += f"/** \\file {filename} */\n"
    result += "/*! \\addtogroup hsl\n"
    result += " *  @{\n"
    result += " */\n"
    result += text
    result += "\n/*! @} */"
    return result

  def process_description(description):
    return Writer.process_description(description, True)

  def get_brief_and_extended_description(text):
    if not text:
      return None

    brief_description = text.split(Parser.HTML_BREAK_STR, 1)[0]
    description = ''

    if brief_description:
      description = text[len(brief_description):]
      if len(description) and description.startswith(Parser.HTML_BREAK_STR):
        description = description[len(Parser.HTML_BREAK_STR):].strip()

    return [brief_description, description]

  def write_function(title, doc, type):
    description = DoxygenWriter.process_description(doc.description)
    returns = DoxygenWriter.process_description(doc.returns)

    if doc.deprecated is not None:
      has_deprecated = True
      deprecated = DoxygenWriter.process_description(doc.deprecated)
    else:
      has_deprecated = False

    text = "    /**"

    descriptions = DoxygenWriter.get_brief_and_extended_description(description)
    if descriptions:
      if descriptions[0]:
        text += f" \\brief {descriptions[0]}\n"
      if descriptions[1]:
        text += f"\n{descriptions[1]}\n"

    params = []
    for param in doc.params:
      param_type = Parser.parse_ref(param.type)
      param_text = f"{param_type} {param.label}"
      if param.default_value:
        param_text += f"={param.default_value}"
      params.append(param_text)
      param_description = DoxygenWriter.process_description(param.description)
      text += f"        \\param {param.label} {param_description}\n"
      pass
    params = ', '.join(params)

    if returns:
      text += f"        \\return {returns}\n"
    if has_deprecated:
      if deprecated:
        text += f"        \\deprecated {deprecated}\n"
      else:
        text += f"        \\deprecated\n"
    text += "    **/\n"

    text += f"    {type} {title}({params});\n"

    return text

  def write_class_function(doc, type):
    title = doc.get_title()
    title_parts = title.rsplit('.', 1)
    if len(title_parts) > 0:
      title = title_parts[-1]

    return DoxygenWriter.write_function(title, doc, type)

  def write_field(doc, type):
    description = DoxygenWriter.process_description(doc.description)

    text = "    /**"
    descriptions = DoxygenWriter.get_brief_and_extended_description(description)
    if descriptions:
      if descriptions[0]:
        text += f" \\brief {descriptions[0]}\n"
      if descriptions[1]:
        text += "\n"
        text += descriptions[1]
    text += "    **/\n"

    text += f"    {type} {doc.title}"
    if doc.default_value is not None:
      text += f" = {doc.default_value}"
    text += ";\n"

    return text

  def write_class(docs, name, desc_doc):
    if desc_doc:
      description = DoxygenWriter.process_description(desc_doc.description)
    else:
      description = None

    text = f"/** \\class {name}\n"
    descriptions = DoxygenWriter.get_brief_and_extended_description(description)
    if descriptions:
      if descriptions[0]:
        text += f" \\brief {descriptions[0]}\n"
      if descriptions[1]:
        text += "\n"
        text += descriptions[1]
    text += "*/\n"
    text += f"class {name}"
    text += " {\n"

    for doc in docs:
      if doc.type == DefType.FUNCTION:
        text += DoxygenWriter.write_class_function(doc, f"public {doc.return_type}")
      elif doc.type == DefType.METHOD:
        text += DoxygenWriter.write_function(doc.title, doc, f"public {doc.return_type}")
      elif doc.type == DefType.CONSTRUCTOR:
        text += DoxygenWriter.write_function(name, doc, "public")
      elif doc.type == DefType.FIELD:
        text += DoxygenWriter.write_field(doc, f"public {doc.value_type}")
      text += "\n"

    text += "};"

    return text

  def write_namespace(class_text, name, desc_doc):
    if desc_doc:
      description = DoxygenWriter.process_description(desc_doc.description)
    else:
      description = None

    text = f"/** \\namespace {name}\n"
    descriptions = DoxygenWriter.get_brief_and_extended_description(description)
    if descriptions:
      if descriptions[0]:
        text += f" \\brief {descriptions[0]}\n"
      if descriptions[1]:
        text += "\n"
        text += descriptions[1]
    text += "*/\n"
    text += f"namespace {name}"
    text += " {\n"
    text += class_text
    text += "\n};"

    return text

  def write_enum(docs, name):
    text = ""

    # TODO: Allow actually writing a description for this
    # This is just to make Doxygen shut up.
    description = f"Documentation for the {name} enum"

    descriptions = DoxygenWriter.get_brief_and_extended_description(description)
    if descriptions:
      text += "/** "
      if descriptions[0]:
        text += f" \\brief {descriptions[0]}\n"
      if descriptions[1]:
        text += "\n"
        text += descriptions[1]
      text += "*/\n"
    text += f"enum {name}"
    text += " {\n"

    for doc in docs:
      title = doc.get_title()
      description = DoxygenWriter.process_description(doc.description)

      text += "    /*!\n"
      text += f"        {description}\n"
      text += "    */\n"
      text += f"    {title},"
      text += "\n"

    text += "};"

    return text

  def write_constant(doc):
    title = doc.get_title()

    text = "/**\n"
    descriptions = DoxygenWriter.get_brief_and_extended_description(doc.description)
    if descriptions:
      if descriptions[0]:
        text += f"    \\brief {descriptions[0]}\n"
      if descriptions[1]:
        text += "\n"
        text += descriptions[1]
    text += "*/\n"
    text += f"const {title};\n"

    return text

  def write_global(doc):
    title = doc.get_title()

    text = "/**\n"
    descriptions = DoxygenWriter.get_brief_and_extended_description(doc.description)
    if descriptions:
      if descriptions[0]:
        text += f"    \\brief {descriptions[0]}\n"
      if descriptions[1]:
        text += "\n" + descriptions[1]
    text += "*/\n"
    text += f"var {title};\n"

    return text

  def generate_files(path):
    # Write base.hsl
    with open(path / 'base.hsl', 'w') as file:
      text = "/** \\defgroup hsl HSL\n"
      text += " * \\brief Documents HSL classes, enums and constants."
      text += " */\n"
      file.write(text)

    # Write namespaces (as in what happens when you use \ns)
    namespace_docs = {}

    for name, info in NamespaceInfo.all.items():
      class_info = info.docs_per_def[DefType.FUNCTION.value]
      class_info += info.docs_per_def[DefType.METHOD.value]
      class_info += info.docs_per_def[DefType.CONSTRUCTOR.value]
      class_info += info.docs_per_def[DefType.FIELD.value]

      if '.' in name:
        if len(class_info) > 0:
          ns_parts = name.rsplit('.', 1)
          if not ns_parts[0] in namespace_docs:
            namespace_docs[ns_parts[0]] = {}
          namespace_docs[ns_parts[0]][ns_parts[1]] = class_info
        continue

      desc_doc = DocDef.find_description(name)

      # Write functions, methods, constructors, and fields
      if len(class_info) > 0:
        filename = path / f"{name}.dox"
        with open(filename, 'w') as file:
          text = DoxygenWriter.write_class(class_info, name, desc_doc)
          text = DoxygenWriter.generate_text_for_file(text)
          file.write(text)

      # Write enums
      enums = info.docs_per_def[DefType.ENUM.value]
      if len(enums) > 0:
        name = name.replace('_*', '')
        enum_filename = f"{name}.hsl"
        filename = path / enum_filename
        with open(filename, 'w') as file:
          text = DoxygenWriter.write_enum(enums, name)
          text = DoxygenWriter.generate_text_for_file(text, enum_filename)
          file.write(text)

    # Write namespaces
    for name in namespace_docs:
      filename = path / f"{name}.dox"
      with open(filename, 'w') as file:
        ns_class = namespace_docs[name]

        class_text = ""

        for klass in ns_class:
          class_name = f"{name}.{klass}"
          class_desc = DocDef.find_description(class_name)

          doc_list = namespace_docs[name][klass]

          class_text += DoxygenWriter.write_class(doc_list, klass, class_desc)
          class_text += "\n"

        desc_doc = DocDef.find_description(name)
        text = DoxygenWriter.write_namespace(class_text, name, desc_doc)
        text = DoxygenWriter.generate_text_for_file(text)
        file.write(text)

    # Write constants
    constants_group = doc_globals.lists[DefType.CONSTANT.value]
    filename = "constants.hsl"
    with open(path / filename, 'w') as file:
      text = "// This is not valid HSL code!\n"
      for doc in constants_group.doc_list:
        text += DoxygenWriter.write_constant(doc)
      text = DoxygenWriter.generate_text_for_file(text, filename)
      file.write(text)

    # Write constants
    globals_group = doc_globals.lists[DefType.GLOBAL_VAR.value]
    filename = "globals.hsl"
    with open(path / filename, 'w') as file:
      text = ""
      for doc in globals_group.doc_list:
        text += DoxygenWriter.write_global(doc)
      text = DoxygenWriter.generate_text_for_file(text, filename)
      file.write(text)
