include meta/prologue.mk

# name of project. used in output binary naming
PROJECT := hatch

# put a ‘1’ for the desired target types to compile
EXEFILE := 1
SOFILE  :=
AFILE   :=

# space-separated path list for #includes
# <system> includes
INCLUDES := source
# "local" includes
INCLUDEL := source

# space-separated library name list for linking
# libraries
LIBS      := assimp ogg vorbis vorbisfile SDL2
LIBDIRS   :=
FWORKS    := Cocoa CoreFoundation CoreServices Foundation OpenGL
FWORKDIRS :=

CFILES := \
	source/Libraries/miniz.c \
	source/Libraries/spng.c \
	source/Libraries/stb_vorbis.c
CPPFILES := \
	source/Engine/Application.cpp \
	source/Engine/Audio/AudioManager.cpp \
	source/Engine/Audio/AudioPlayback.cpp \
	source/Engine/Bytecode/Bytecode.cpp \
	source/Engine/Bytecode/BytecodeDebugger.cpp \
	source/Engine/Bytecode/Compiler.cpp \
	source/Engine/Bytecode/GarbageCollector.cpp \
	source/Engine/Bytecode/ScriptEntity.cpp \
	source/Engine/Bytecode/ScriptManager.cpp \
	source/Engine/Bytecode/SourceFileMap.cpp \
	source/Engine/Bytecode/StandardLibrary.cpp \
	source/Engine/Bytecode/TypeImpl/ArrayImpl.cpp \
	source/Engine/Bytecode/TypeImpl/EntityImpl.cpp \
	source/Engine/Bytecode/TypeImpl/FontImpl.cpp \
	source/Engine/Bytecode/TypeImpl/FunctionImpl.cpp \
	source/Engine/Bytecode/TypeImpl/InstanceImpl.cpp \
	source/Engine/Bytecode/TypeImpl/MapImpl.cpp \
	source/Engine/Bytecode/TypeImpl/MaterialImpl.cpp \
	source/Engine/Bytecode/TypeImpl/ShaderImpl.cpp \
	source/Engine/Bytecode/TypeImpl/StreamImpl.cpp \
	source/Engine/Bytecode/TypeImpl/StringImpl.cpp \
	source/Engine/Bytecode/TypeImpl/TextureImpl.cpp \
	source/Engine/Bytecode/TypeImpl/TypeImpl.cpp \
	source/Engine/Bytecode/Types.cpp \
	source/Engine/Bytecode/Value.cpp \
	source/Engine/Bytecode/ValuePrinter.cpp \
	source/Engine/Bytecode/VMThread.cpp \
	source/Engine/Bytecode/VMThreadDebugger.cpp \
	source/Engine/Data/DefaultFonts.cpp \
	source/Engine/Diagnostics/Clock.cpp \
	source/Engine/Diagnostics/Log.cpp \
	source/Engine/Diagnostics/Memory.cpp \
	source/Engine/Diagnostics/MemoryPools.cpp \
	source/Engine/Diagnostics/PerformanceMeasure.cpp \
	source/Engine/Diagnostics/PerformanceViewer.cpp \
	source/Engine/Diagnostics/RemoteDebug.cpp \
	source/Engine/Error.cpp \
	source/Engine/Extensions/Discord.cpp \
	source/Engine/Filesystem/Directory.cpp \
	source/Engine/Filesystem/File.cpp \
	source/Engine/Filesystem/Path.cpp \
	source/Engine/Filesystem/VFS/ArchiveVFS.cpp \
	source/Engine/Filesystem/VFS/FileSystemVFS.cpp \
	source/Engine/Filesystem/VFS/HatchVFS.cpp \
	source/Engine/Filesystem/VFS/MemoryCache.cpp \
	source/Engine/Filesystem/VFS/MemoryVFS.cpp \
	source/Engine/Filesystem/VFS/VFSEntry.cpp \
	source/Engine/Filesystem/VFS/VFSProvider.cpp \
	source/Engine/Filesystem/VFS/VirtualFileSystem.cpp \
	source/Engine/Graphics.cpp \
	source/Engine/Hashing/CombinedHash.cpp \
	source/Engine/Hashing/CRC32.cpp \
	source/Engine/Hashing/FNV1A.cpp \
	source/Engine/Hashing/MD5.cpp \
	source/Engine/Hashing/Murmur.cpp \
	source/Engine/Input/Controller.cpp \
	source/Engine/Input/InputAction.cpp \
	source/Engine/Input/InputPlayer.cpp \
	source/Engine/InputManager.cpp \
	source/Engine/IO/Compression/Huffman.cpp \
	source/Engine/IO/Compression/LZ11.cpp \
	source/Engine/IO/Compression/LZSS.cpp \
	source/Engine/IO/Compression/RunLength.cpp \
	source/Engine/IO/Compression/ZLibStream.cpp \
	source/Engine/IO/FileStream.cpp \
	source/Engine/IO/MemoryStream.cpp \
	source/Engine/IO/NetworkStream.cpp \
	source/Engine/IO/ResourceStream.cpp \
	source/Engine/IO/SDLStream.cpp \
	source/Engine/IO/Serializer.cpp \
	source/Engine/IO/StandardIOStream.cpp \
	source/Engine/IO/Stream.cpp \
	source/Engine/IO/TextStream.cpp \
	source/Engine/IO/VirtualFileStream.cpp \
	source/Engine/Main.cpp \
	source/Engine/Math/Clipper.cpp \
	source/Engine/Math/Ease.cpp \
	source/Engine/Math/Geometry.cpp \
	source/Engine/Math/Math.cpp \
	source/Engine/Math/Matrix4x4.cpp \
	source/Engine/Math/Random.cpp \
	source/Engine/Math/Vector.cpp \
	source/Engine/Media/Decoder.cpp \
	source/Engine/Media/Decoders/AudioDecoder.cpp \
	source/Engine/Media/Decoders/VideoDecoder.cpp \
	source/Engine/Media/MediaPlayer.cpp \
	source/Engine/Media/MediaSource.cpp \
	source/Engine/Media/Utils/MediaPlayerState.cpp \
	source/Engine/Media/Utils/PtrBuffer.cpp \
	source/Engine/Media/Utils/RingBuffer.cpp \
	source/Engine/Network/AndroidWifiP2P.cpp \
	source/Engine/Network/HTTP.cpp \
	source/Engine/Network/WebSocketClient.cpp \
	source/Engine/Rendering/D3D/D3DRenderer.cpp \
	source/Engine/Rendering/FaceInfo.cpp \
	source/Engine/Rendering/GL/GLRenderer.cpp \
	source/Engine/Rendering/GL/GLShader.cpp \
	source/Engine/Rendering/GL/GLShaderBuilder.cpp \
	source/Engine/Rendering/GL/GLShaderContainer.cpp \
	source/Engine/Rendering/Material.cpp \
	source/Engine/Rendering/ModelRenderer.cpp \
	source/Engine/Rendering/PolygonRenderer.cpp \
	source/Engine/Rendering/SDL2/SDL2Renderer.cpp \
	source/Engine/Rendering/Shader.cpp \
	source/Engine/Rendering/Software/PolygonRasterizer.cpp \
	source/Engine/Rendering/Software/Scanline.cpp \
	source/Engine/Rendering/Software/SoftwareRenderer.cpp \
	source/Engine/Rendering/Texture.cpp \
	source/Engine/Rendering/TextureReference.cpp \
	source/Engine/Rendering/VertexBuffer.cpp \
	source/Engine/ResourceTypes/Font.cpp \
	source/Engine/ResourceTypes/Image.cpp \
	source/Engine/ResourceTypes/ImageFormats/GIF.cpp \
	source/Engine/ResourceTypes/ImageFormats/ImageFormat.cpp \
	source/Engine/ResourceTypes/ImageFormats/JPEG.cpp \
	source/Engine/ResourceTypes/ImageFormats/PNG.cpp \
	source/Engine/ResourceTypes/IModel.cpp \
	source/Engine/ResourceTypes/ISound.cpp \
	source/Engine/ResourceTypes/ISprite.cpp \
	source/Engine/ResourceTypes/ModelFormats/HatchModel.cpp \
	source/Engine/ResourceTypes/ModelFormats/Importer.cpp \
	source/Engine/ResourceTypes/ModelFormats/MD3Model.cpp \
	source/Engine/ResourceTypes/ModelFormats/RSDKModel.cpp \
	source/Engine/ResourceTypes/ResourceManager.cpp \
	source/Engine/ResourceTypes/SceneFormats/HatchSceneReader.cpp \
	source/Engine/ResourceTypes/SceneFormats/RSDKSceneReader.cpp \
	source/Engine/ResourceTypes/SceneFormats/TiledMapReader.cpp \
	source/Engine/ResourceTypes/SoundFormats/OGG.cpp \
	source/Engine/ResourceTypes/SoundFormats/SoundFormat.cpp \
	source/Engine/ResourceTypes/SoundFormats/WAV.cpp \
	source/Engine/Scene.cpp \
	source/Engine/Scene/SceneInfo.cpp \
	source/Engine/Scene/SceneLayer.cpp \
	source/Engine/Scene/View.cpp \
	source/Engine/TextFormats/INI/INI.cpp \
	source/Engine/TextFormats/XML/XMLParser.cpp \
	source/Engine/Types/Camera.cpp \
	source/Engine/Types/DrawGroupList.cpp \
	source/Engine/Types/Entity.cpp \
	source/Engine/Types/ObjectList.cpp \
	source/Engine/Types/ObjectRegistry.cpp \
	source/Engine/Types/Property.cpp \
	source/Engine/Types/Tileset.cpp \
	source/Engine/Utilities/ColorUtils.cpp \
	source/Engine/Utilities/PrintBuffer.cpp \
	source/Engine/Utilities/Screenshot.cpp \
	source/Engine/Utilities/StringUtils.cpp \
	source/Libraries/Clipper2/clipper.engine.cpp \
	source/Libraries/Clipper2/clipper.offset.cpp \
	source/Libraries/Clipper2/clipper.rectclip.cpp \
	source/Libraries/linenoise-ng/linenoise.cpp \
	source/Libraries/linenoise-ng/wcwidth.cpp \
	source/Libraries/poly2tri/common/shapes.cpp \
	source/Libraries/poly2tri/sweep/advancing_front.cpp \
	source/Libraries/poly2tri/sweep/cdt.cpp \
	source/Libraries/poly2tri/sweep/sweep.cpp \
	source/Libraries/poly2tri/sweep/sweep_context.cpp
MFILES := \
	source/Engine/Platforms/MacOS/Filesystem.m
PRVHFILES := \
	source/Libraries/ankerl/stl.h \
	source/Libraries/ankerl/unordered_dense.h \
	source/Libraries/Clipper2/clipper.core.h \
	source/Libraries/Clipper2/clipper.engine.h \
	source/Libraries/Clipper2/clipper.export.h \
	source/Libraries/Clipper2/clipper.h \
	source/Libraries/Clipper2/clipper.minkowski.h \
	source/Libraries/Clipper2/clipper.offset.h \
	source/Libraries/Clipper2/clipper.rectclip.h \
	source/Libraries/Clipper2/clipper.version.h \
	source/Libraries/discord_game_sdk.h \
	source/Libraries/jsmn.h \
	source/Libraries/linenoise-ng/linenoise.h \
	source/Libraries/miniz.h \
	source/Libraries/nanoprintf.h \
	source/Libraries/poly2tri/common/dll_symbol.h \
	source/Libraries/poly2tri/common/shapes.h \
	source/Libraries/poly2tri/common/utils.h \
	source/Libraries/poly2tri/poly2tri.h \
	source/Libraries/poly2tri/sweep/advancing_front.h \
	source/Libraries/poly2tri/sweep/cdt.h \
	source/Libraries/poly2tri/sweep/sweep.h \
	source/Libraries/poly2tri/sweep/sweep_context.h \
	source/Libraries/spng.h \
	source/Libraries/stb_image.h \
	source/Libraries/stb_rect_pack.h \
	source/Libraries/stb_truetype.h \
	source/Libraries/stb_vorbis.h \
	source/Libraries/utfcpp/utf8.h \
	source/Libraries/utfcpp/utf8/checked.h \
	source/Libraries/utfcpp/utf8/core.h \
	source/Libraries/utfcpp/utf8/cpp11.h \
	source/Libraries/utfcpp/utf8/cpp17.h \
	source/Libraries/utfcpp/utf8/cpp20.h \
	source/Libraries/utfcpp/utf8/unchecked.h
PUBHFILES := \
	source/Engine/Application.h \
	source/Engine/Audio/AudioChannel.h \
	source/Engine/Audio/AudioIncludes.h \
	source/Engine/Audio/AudioManager.h \
	source/Engine/Audio/AudioPlayback.h \
	source/Engine/Bytecode/Bytecode.h \
	source/Engine/Bytecode/BytecodeDebugger.h \
	source/Engine/Bytecode/Compiler.h \
	source/Engine/Bytecode/CompilerEnums.h \
	source/Engine/Bytecode/GarbageCollector.h \
	source/Engine/Bytecode/ScriptEntity.h \
	source/Engine/Bytecode/ScriptManager.h \
	source/Engine/Bytecode/SourceFileMap.h \
	source/Engine/Bytecode/StandardLibrary.h \
	source/Engine/Bytecode/TypeImpl/ArrayImpl.h \
	source/Engine/Bytecode/TypeImpl/EntityImpl.h \
	source/Engine/Bytecode/TypeImpl/FontImpl.h \
	source/Engine/Bytecode/TypeImpl/FunctionImpl.h \
	source/Engine/Bytecode/TypeImpl/InstanceImpl.h \
	source/Engine/Bytecode/TypeImpl/MapImpl.h \
	source/Engine/Bytecode/TypeImpl/MaterialImpl.h \
	source/Engine/Bytecode/TypeImpl/ShaderImpl.h \
	source/Engine/Bytecode/TypeImpl/StreamImpl.h \
	source/Engine/Bytecode/TypeImpl/StringImpl.h \
	source/Engine/Bytecode/TypeImpl/TypeImpl.h \
	source/Engine/Bytecode/Types.h \
	source/Engine/Bytecode/VMThread.h \
	source/Engine/Bytecode/VMThreadDebugger.h \
	source/Engine/Bytecode/Value.h \
	source/Engine/Bytecode/ValuePrinter.h \
	source/Engine/Data/DefaultFonts.h \
	source/Engine/Diagnostics/Clock.h \
	source/Engine/Diagnostics/Log.h \
	source/Engine/Diagnostics/Memory.h \
	source/Engine/Diagnostics/MemoryPools.h \
	source/Engine/Diagnostics/PerformanceMeasure.h \
	source/Engine/Diagnostics/PerformanceTypes.h \
	source/Engine/Diagnostics/PerformanceViewer.h \
	source/Engine/Diagnostics/RemoteDebug.h \
	source/Engine/Error.h \
	source/Engine/Exceptions/CompilerErrorException.h \
	source/Engine/Exceptions/ScriptException.h \
	source/Engine/Extensions/Discord.h \
	source/Engine/Filesystem/Directory.h \
	source/Engine/Filesystem/File.h \
	source/Engine/Filesystem/Path.h \
	source/Engine/Filesystem/VFS/ArchiveVFS.h \
	source/Engine/Filesystem/VFS/FileSystemVFS.h \
	source/Engine/Filesystem/VFS/HatchVFS.h \
	source/Engine/Filesystem/VFS/MemoryCache.h \
	source/Engine/Filesystem/VFS/MemoryVFS.h \
	source/Engine/Filesystem/VFS/VFSEntry.h \
	source/Engine/Filesystem/VFS/VFSProvider.h \
	source/Engine/Filesystem/VFS/VirtualFileSystem.h \
	source/Engine/Graphics.h \
	source/Engine/Hashing/CRC32.h \
	source/Engine/Hashing/CombinedHash.h \
	source/Engine/Hashing/FNV1A.h \
	source/Engine/Hashing/MD5.h \
	source/Engine/Hashing/Murmur.h \
	source/Engine/IO/Compression/CompressionEnums.h \
	source/Engine/IO/Compression/Huffman.h \
	source/Engine/IO/Compression/LZ11.h \
	source/Engine/IO/Compression/LZSS.h \
	source/Engine/IO/Compression/RunLength.h \
	source/Engine/IO/Compression/ZLibStream.h \
	source/Engine/IO/FileStream.h \
	source/Engine/IO/MemoryStream.h \
	source/Engine/IO/NetworkStream.h \
	source/Engine/IO/ResourceStream.h \
	source/Engine/IO/SDLStream.h \
	source/Engine/IO/Serializer.h \
	source/Engine/IO/StandardIOStream.h \
	source/Engine/IO/Stream.h \
	source/Engine/IO/TextStream.h \
	source/Engine/IO/VirtualFileStream.h \
	source/Engine/Includes/BijectiveMap.h \
	source/Engine/Includes/DateTime.h \
	source/Engine/Includes/Endian.h \
	source/Engine/Includes/HashMap.h \
	source/Engine/Includes/Operation.h \
	source/Engine/Includes/OrderedHashMap.h \
	source/Engine/Includes/Standard.h \
	source/Engine/Includes/StandardSDL2.h \
	source/Engine/Includes/Token.h \
	source/Engine/Includes/Version.h \
	source/Engine/Input/Controller.h \
	source/Engine/Input/ControllerRumble.h \
	source/Engine/Input/Input.h \
	source/Engine/Input/InputAction.h \
	source/Engine/Input/InputPlayer.h \
	source/Engine/InputManager.h \
	source/Engine/Math/Clipper.h \
	source/Engine/Math/Ease.h \
	source/Engine/Math/FixedPoint.h \
	source/Engine/Math/Geometry.h \
	source/Engine/Math/GeometryTypes.h \
	source/Engine/Math/Math.h \
	source/Engine/Math/Matrix4x4.h \
	source/Engine/Math/Random.h \
	source/Engine/Math/Vector.h \
	source/Engine/Math/VectorTypes.h \
	source/Engine/Media/Decoder.h \
	source/Engine/Media/Decoders/AudioDecoder.h \
	source/Engine/Media/Decoders/VideoDecoder.h \
	source/Engine/Media/Includes/AVCodec.h \
	source/Engine/Media/Includes/AVFormat.h \
	source/Engine/Media/Includes/AVUtils.h \
	source/Engine/Media/Includes/SWResample.h \
	source/Engine/Media/Includes/SWScale.h \
	source/Engine/Media/MediaPlayer.h \
	source/Engine/Media/MediaSource.h \
	source/Engine/Media/Utils/Codec.h \
	source/Engine/Media/Utils/MediaPlayerState.h \
	source/Engine/Media/Utils/PtrBuffer.h \
	source/Engine/Media/Utils/RingBuffer.h \
	source/Engine/Network/HTTP.h \
	source/Engine/Network/WebSocketClient.h \
	source/Engine/Network/WebSocketIncludes.h \
	source/Engine/Platforms/Capability.h \
	source/Engine/Platforms/MacOS/Filesystem.h \
	source/Engine/Platforms/iOS/MediaPlayer.h \
	source/Engine/Rendering/3D.h \
	source/Engine/Rendering/D3D/D3DRenderer.h \
	source/Engine/Rendering/Enums.h \
	source/Engine/Rendering/FaceInfo.h \
	source/Engine/Rendering/GL/GLRenderer.h \
	source/Engine/Rendering/GL/GLShader.h \
	source/Engine/Rendering/GL/GLShaderBuilder.h \
	source/Engine/Rendering/GL/GLShaderContainer.h \
	source/Engine/Rendering/GL/Includes.h \
	source/Engine/Rendering/GL/ShaderIncludes.h \
	source/Engine/Rendering/GL/Structs.h \
	source/Engine/Rendering/GameTexture.h \
	source/Engine/Rendering/GraphicsFunctions.h \
	source/Engine/Rendering/Material.h \
	source/Engine/Rendering/Mesh.h \
	source/Engine/Rendering/Metal/Includes.h \
	source/Engine/Rendering/Metal/MetalFuncs.h \
	source/Engine/Rendering/ModelRenderer.h \
	source/Engine/Rendering/PolygonRenderer.h \
	source/Engine/Rendering/SDL2/SDL2MetalFunc.h \
	source/Engine/Rendering/SDL2/SDL2Renderer.h \
	source/Engine/Rendering/Scene3D.h \
	source/Engine/Rendering/Shader.h \
	source/Engine/Rendering/Software/Contour.h \
	source/Engine/Rendering/Software/PolygonRasterizer.h \
	source/Engine/Rendering/Software/Scanline.h \
	source/Engine/Rendering/Software/SoftwareEnums.h \
	source/Engine/Rendering/Software/SoftwareRenderer.h \
	source/Engine/Rendering/Texture.h \
	source/Engine/Rendering/TextureReference.h \
	source/Engine/Rendering/VertexBuffer.h \
	source/Engine/Rendering/ViewTexture.h \
	source/Engine/ResourceTypes/Font.h \
	source/Engine/ResourceTypes/IModel.h \
	source/Engine/ResourceTypes/ISound.h \
	source/Engine/ResourceTypes/ISprite.h \
	source/Engine/ResourceTypes/Image.h \
	source/Engine/ResourceTypes/ImageFormats/GIF.h \
	source/Engine/ResourceTypes/ImageFormats/ImageFormat.h \
	source/Engine/ResourceTypes/ImageFormats/JPEG.h \
	source/Engine/ResourceTypes/ImageFormats/PNG.h \
	source/Engine/ResourceTypes/ModelFormats/HatchModel.h \
	source/Engine/ResourceTypes/ModelFormats/Importer.h \
	source/Engine/ResourceTypes/ModelFormats/MD3Model.h \
	source/Engine/ResourceTypes/ModelFormats/RSDKModel.h \
	source/Engine/ResourceTypes/ResourceManager.h \
	source/Engine/ResourceTypes/ResourceType.h \
	source/Engine/ResourceTypes/SceneFormats/HatchSceneReader.h \
	source/Engine/ResourceTypes/SceneFormats/HatchSceneTypes.h \
	source/Engine/ResourceTypes/SceneFormats/RSDKSceneReader.h \
	source/Engine/ResourceTypes/SceneFormats/TiledMapReader.h \
	source/Engine/ResourceTypes/SoundFormats/OGG.h \
	source/Engine/ResourceTypes/SoundFormats/SoundFormat.h \
	source/Engine/ResourceTypes/SoundFormats/WAV.h \
	source/Engine/Scene.h \
	source/Engine/Scene/LayerGroup.h \
	source/Engine/Scene/SceneConfig.h \
	source/Engine/Scene/SceneEnums.h \
	source/Engine/Scene/SceneInfo.h \
	source/Engine/Scene/SceneLayer.h \
	source/Engine/Scene/ScrollingInfo.h \
	source/Engine/Scene/TileAnimation.h \
	source/Engine/Scene/TileConfig.h \
	source/Engine/Scene/TileSpriteInfo.h \
	source/Engine/Scene/View.h \
	source/Engine/Sprites/Animation.h \
	source/Engine/TextFormats/INI/INI.h \
	source/Engine/TextFormats/INI/INIStructs.h \
	source/Engine/TextFormats/XML/XMLNode.h \
	source/Engine/TextFormats/XML/XMLParser.h \
	source/Engine/Types/Camera.h \
	source/Engine/Types/Collision.h \
	source/Engine/Types/DrawGroupList.h \
	source/Engine/Types/Entity.h \
	source/Engine/Types/EntityTypes.h \
	source/Engine/Types/ObjectList.h \
	source/Engine/Types/ObjectRegistry.h \
	source/Engine/Types/Property.h \
	source/Engine/Types/Tileset.h \
	source/Engine/Utilities/ColorUtils.h \
	source/Engine/Utilities/PrintBuffer.h \
	source/Engine/Utilities/Screenshot.h \
	source/Engine/Utilities/StringUtils.h

DEFINES := \
	_THREAD_SAFE \
	GL_SILENCE_DEPRECATION \
	MACOSX \
	TARGET_NAME=\"$(PROJECT)\" \
	USING_ASSIMP \
	USING_OPENGL

CFLAGS := -std=c11
CXXFLAGS := \
	-std=c++17 \
	-Wno-pedantic \
	-Wno-unused-but-set-variable \
	-Wno-unused-function \
	-Wno-unused-label \
	-Wno-unused-lambda-capture \
	-Wno-unused-value \
	-Wno-unused-variable

# the linker has to care about this too, unfortunately
LDFLAGS := -std=c++17 -fuse-ld=lld

# Hatch uses meta/ instead of etc/
FMTFLAGS := -style=file:meta/clang-format.yml

# this defines all our usual targets
include meta/epilogue.mk
