#ifndef ENGINE_AUDIO_AUDIOINCLUDES_H
#define ENGINE_AUDIO_AUDIOINCLUDES_H

#define AUDIO_FIRST_LOAD_SAMPLE_BOOST 4

enum { MusicFade_None, MusicFade_Out, MusicFade_In };

#endif /* ENGINE_AUDIO_AUDIOINCLUDES_H */
